services:
  app:
    build: .
    container_name: chat-server
    ports:
      -  "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  redis:
    image: redis
    container_name: chat-redis
    ports:
      -  "6379:6379"
